name: merge dependabot
on: 
  pull_request:
    types: [labeled]

jobs:
  merge:
    if: ${{github.event.label.name == 'dependabot'}}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install tparse
        run: go install github.com/mfridman/tparse@v0.12.2
      - run: |
          go mod tidy
      - run: |
          go test -v ./...
      - run: |
          git config --local user.name 'Daisuke Maki'
          git config --local user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Run tidy" || echo "No changes to commit"
          git push origin "HEAD:${GITHUB_HEAD_REF}" || echo "Nothing to push"
          gh pr review --approve "$PR_URL"
          gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}